spring:
  application:
    name: service-pay
  cloud:
    config:
      uri: http://localhost:7001/
      profile: dev
      label: master

server:
  port: 8082

#eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#  client:
#    service-url:
#      defaultZone: http://192.168.231.135:9001/eureka/
##      defaultZone: http://localhost:9001/eureka/

# 日志
#logging:
#  file:
##    path: E:/logs/pay
#    path: /home/javaweb/logs/pay
