spring:
  application:
    name: base-pay

server:
  port: 8082

eureka:
  instance:
    hostname: 10.6.223.241
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    service-url:
      defaultZone: http://192.168.231.135:9001/eureka/

