server:
  port: 9091

spring:
  application:
    name: base-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/

zuul:
  routes:
    pay.serviceId: service-pay
    pay.path: /pay/*
    order.serviceId: service-order
    order.path: /order/*