spring:
  application:
    name: zuul-server

server:
  port: 6001

############# Eureka、log 配置信息从config读取 #####################
#eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#  client:
#    service-url:
#      defaultZone: http://192.168.231.135:9001/eureka/
##      defaultZone: http://localhost:9001/eureka/
## 日志
#logging:
#  file:
##    path: E:/logs/zuul
#    path: /home/javaweb/logs/zuul

#路由配置
zuul:
  routes:
    pay:
      service-id: service-pay
      path: /pay/**
    order:
      service-id: service-order
      path: /order/**

